name: Api v1.1
on:
  push:
    branches:
      - swaggerhub-finexio-api_doc-v1_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_API_KEY }}:6272ada3f905240021181c4a
           
          # OPTIONAL CONFIG, use if necessary
          # oas-file-path: './swagger.json'
          api-version: 'v1.1.0'
