name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_API_KEY }}:61b09c1232f6729907ed75f8
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './output/swagger.json'
          # api-version: 'v1.0.0'
