name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi output/swagger.json --key=${{ secrets.README_API_KEY }} --id=61b09c1232f6729907ed75f8
           
       
