name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: bBcDCtTB0i7QyuIzI3JSlAzJgazDoo48:614b6b9bac92ce3c28d5b449
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './output/swagger.json'
          # api-version: 'v1.0.0'
