name: Finexio API v2
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi output/v2.0.json --key=rdme_xn8s9hc6f3f2c800d8e764e5710e90fd176633f6176d42fd600ad5aa3c2cb6e33e4f2f --id=6272ada3f905240021181c4a
