name: Finexio API v2
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi output/v2.0.json --key=rdme_xn8s9h2e7eb6f2d6d7019cafd6b492fed2e0bbd93276f0ee9d82bdd87ebe0272227b42 --id=6272ada3f905240021181c4a